runners:
  emr:
    # 環境変数 AWS_ACCESS_KEY_ID と AWS_SECRET_ACCESS_KEY を設定
    # aws_access_key_id: xxxx
    # aws_secret_access_key: xxxx
    region: ap-northeast-1
    instance_fleets:
      - InstanceFleetType: MASTER
        InstanceTypeConfigs:
          - InstanceType: m1.medium
        TargetOnDemandCapacity: 1
      - InstanceFleetType: CORE
        TargetSpotCapacity: 2
        TargetOnDemandCapacity: 2
        LaunchSpecifications:
          SpotSpecification:
            TimeoutDurationMinutes: 20
            TimeoutAction: SWITCH_TO_ON_DEMAND
        InstanceTypeConfigs:
          - InstanceType: m1.medium
            BidPriceAsPercentageOfOnDemandPrice: 50
            WeightedCapacity: 1
          - InstanceType: m1.large
            BidPriceAsPercentageOfOnDemandPrice: 50
            WeightedCapacity: 2