version: '3'
services:
  fluentd:
    build:
      context: .
      dockerfile: Dockerfile-fluentd
    container_name: fluentd
    volumes:
      - "./fluentd/log:/fluentd/log"
      - "./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf"
      - "./nginx/log:/var/log/nginx"
    environment:
      FLUENTD_OPT: "-vv"
      FLUENTD_CONF: "fluentd.conf"
      TZ: "Asia/Tokyo"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    ports:
      - "80:80"
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./nginx/log:/var/log/nginx"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_pass
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
